openapi: 3.0.1
info:
    title: Jobs API
    description: API for managing jobs
    version: 1.0.0
servers:
    - url: https://jobs-api-backend-us19.onrender.com/api/v1

paths:
    /auth/register:
        post:
            tags:
                - Auth
            summary: Register a new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                email:
                                    type: string
                                password:
                                    type: string
                            example:
                                name: "saw"
                                email: "saw@gmail.com"
                                password: "456"
            responses:
                "201":
                    description: User registered successfully
                "400":
                    description: Bad request

    /auth/login:
        post:
            tags:
                - Auth
            summary: Log in a user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
                            example:
                                email: "saw@gmail.com"
                                password: "456"
            responses:
                "200":
                    description: Login successful
                "401":
                    description: Unauthorized

    /jobs:
        get:
            tags:
                - Jobs
            summary: Get all jobs
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: List of jobs
                "401":
                    description: Unauthorized

        post:
            tags:
                - Jobs
            summary: Create a new job
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                company:
                                    type: string
                                position:
                                    type: string
                                status:
                                    type: string
                            example:
                                company: "Meta"
                                position: "Data Analyst"
                                status: "interview"
            responses:
                "201":
                    description: Job created successfully
                "401":
                    description: Unauthorized

    /jobs/{jobId}:
        get:
            tags:
                - Jobs
            summary: Get a job by ID
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: jobId
                  schema:
                      type: string
                  required: true
                  description: Numeric ID of the user to get
            responses:
                "200":
                    description: Job details
                "404":
                    description: Job not found

        put:
            tags:
                - Jobs
            summary: Update a job by ID
            parameters:
                - in: path
                  name: jobId
                  schema:
                      type: string
                  required: true
                  description: Numeric ID of the user to edit
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                company:
                                    type: string
                                position:
                                    type: string
                                status:
                                    type: string
                            example:
                                company: "Meta"
                                position: "Data Analyst"
                                statis: "interview"
            responses:
                "200":
                    description: Job updated successfully
                "404":
                    description: Job not found

        delete:
            tags:
                - Jobs
            summary: Delete a job by ID
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: jobId
                  schema:
                      type: string
                  required: true
                  description: Numeric ID of the user to delete
            responses:
                "200":
                    description: Job deleted successfully
                "404":
                    description: Job not found

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
